"""Added has_voted field to users table

Revision ID: 3d787976650c
Revises: 
Create Date: 2023-12-01 00:47:10.828150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d787976650c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('candidate_position_association', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', sa.Boolean(), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.drop_column('has_voted')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_position_association', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
