"""Added has_regsitered field

Revision ID: 60c77038cb5f
Revises: 2f311f833051
Create Date: 2023-12-08 22:42:28.943167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60c77038cb5f'
down_revision = '2f311f833051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('candidate_position_association', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=126), nullable=False))
        batch_op.add_column(sa.Column('has_voted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_registered', sa.Boolean(), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.drop_column('has_registered')
        batch_op.drop_column('has_voted')
        batch_op.drop_column('password')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_position_association', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
