"""About to import csv

Revision ID: a1e2e1ed8de7
Revises: 3d787976650c
Create Date: 2023-12-08 21:33:45.826828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1e2e1ed8de7'
down_revision = '3d787976650c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('candidate_position_association', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=126), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('faculty', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               type_=sa.String(length=36, collation='utf8_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=126), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=126), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.drop_column('department')
        batch_op.drop_column('faculty')
        batch_op.drop_column('level')
        batch_op.drop_column('gender')
        batch_op.drop_column('name')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('candidate_position_association', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('position_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
